### ISSUE TITLE
Differentiating unique "job Id" from generic "job name"

### ISSUE THREAD

**Issue by balis** [wfcommons/WfFormat#1]
I found it really helpful to have *generic* job names in workflow graphs that identify a "class" of the job, e.g. "mDiffFit". It allows identifying jobs that are similar which can be very useful. I suggest to introduce such a generic job name to the WfCommons format, in addition to a unique id which is needed to specify parents/children relationships, but otherwise is not meaningful.

**Comment by rafaelfsilva** [comment]
Thank you for the suggestions @balis, we will be considering them for the next release.

**Comment by rafaelfsilva** [comment]
In the version 1.2 of the schema, we will provide 2 new properties for the jobs:

- `id`: Job unique ID (e.g., ID0000001).
- `category`: Job category (can be used, for example, to define jobs that use the same program).

We believe these properties will fulfill the need described in your request.
