### ISSUE TITLE
Allow tasks to be associated with multiple machines?

### ISSUE THREAD

**Issue by wrwilliams** [wfcommons/WfFormat#4]
# Problem

A workflow may include individual tasks that execute on multiple nodes (MPI or similar parallelism) as well as other tasks that execute on those individual nodes in parallel. As a task is only allowed to specify one "machine" where it will execute, it's not possible to distinguish single-node and multi-node tasks easily. So, if we have nodes N1-N4, and T0 runs on all four nodes, T1 through T4 are its children running independently on N1-N4 respectively, and T5 again runs on all four nodes as a child of T1-T4, how do we best represent this in wfcommons?

# Preferred Solution

Allow "machines" as a list per task as well as per workflow

# Alternatives (and why they're not great)

## Make the "machine" the biggest chunk of nodes on which any task executes, with core count etc aggregated across nodes

This loses the information that T1-T4 are independent and not interfering with each other. Also, the "hostname" for a small allocation within a large partition on a large cluster becomes awkward to try to generate meaningfully.

## Treat an MPI-parallel task as multiple tasks, one per node (or process)

This maps really badly to how most workflow systems would specify a multi-node MPI-parallel task

## Make the "machine" the host where rank 0 runs

Loses information about all other nodes and looks like one node was oversubscribed

If I'm missing some "natural" way to represent these tasks, please let me know.

**Comment by bertwesarg** [comment]
@rafaelfsilva is this something which can be solved in 1.5?

**Comment by rafaelfsilva** [comment]
Hi @bertwesarg , we will be adding this feature for 1.5, hopefully within the next days.
