### ISSUE TITLE
Explanation of versioning scheme

### ISSUE THREAD

**Issue by mxmlnkn** [wfcommons/WfFormat#7]
What kind of semantics is the version number supposed to convey?

Coming from semantic versioning, my expectation would have been: major.minor in which a new major version is not downwards compatible to the previous major version and new minor versions introduce new features/fields, required or not, but to keep downwards compatibility, they should not remove (including name changes) any pre-existing required fields.

This assumption of mine was already invalidated with the jump from 1.3 to 1.4 because the **required** fields `makespan` and `size` (for files) have been renamed to `makespanInSeconds` and `sizeInBytes`. Any tool checking for wfformat version >= 1.3 && version < 2 and depending on the existence of a `makespan` and `size` field would fail miserably with wfformat 1.4.

While these two changes were easy enough to update, now with wfformat 1.5, the whole core hierarchy changed from `workflow -> tasks` to `workflow -> specification -> tasks` among many other changes. While, arguably wfformat 1.4 should already have been named wfformat 2, the changes were still somewhat digestible, but I can't see any reasoning for calling it wfformat 1.5 instead of wfformat 2 with such major changes.

**Comment by rafaelfsilva** [comment]
Hi @mxmlnkn,

I understand your comment and agree that the changes have been substantial. The preliminary versions of WfFormat were too narrow, covering only a few workflow use cases. We are currently working on v2.0, which will introduce significant changes to WfFormat and aim to cover a broader range of workflow instances, including both static and dynamic workflows. The current v1.5 will be the last release to include changes incompatible with previous versions. From v2.0 onwards, we intend to carefully consider the impact of changes and ensure backward compatibility.

Thank you!
